import type { Metadata } from "next";

import { Inter } from "next/font/google";
import "./globals.css";
import StoreProvider from "./StoreProvider";
import { Toaster } from "@/components/ui/toaster";
import UserSessionProvider from "./_components/UserSessionComp/UserSessionProvider";
import { MessageOpenProvider } from "@/context/comment";
import BottomNav from "./_components/BottomNav";
// import NavProgress from "./_components/NavProgress";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>

      </head>
      <body className={inter.className}>
        <StoreProvider>
          <MessageOpenProvider>{children}</MessageOpenProvider>
          <Toaster />
          <UserSessionProvider />
          <BottomNav />

        </StoreProvider>

        {/* <NavProgress /> */}
      </body>
    </html>
  );
}
export default RootLayout;
