
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import StoreProvider from "./StoreProvider";
import { Toaster } from "@/components/ui/toaster";
import { PaginationProvider } from "@/context/pagganition";
import UserSessionProvider from "./_componsents/UserSessionComp/UserSessionProvider";
import { wrapper } from "@/store/store";
import { MessageOpenProvider } from "@/context/comment";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
 function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body className={inter.className}>

      
      <StoreProvider>
      <MessageOpenProvider>


        {children}
      </MessageOpenProvider>
        <Toaster /> 
        <UserSessionProvider/>
      </StoreProvider>

        </body>



    </html>
  );
}
export default RootLayout
